OPENAI_API_TYPE: "azure"
OPENAI_API_BASE: "https://autoagents-ca-east.openai.azure.com/"  # YOUR_API_KEY
OPENAI_API_KEY: "2864ce19a46540b2a0943df607ca6225"  # YOUR_API_KEY
OPENAI_API_VERSION: "2023-08-01-preview" # gpt-4, gpt-3.5-turbo, etc.
DEPLOYMENT_NAME: "gpt-4" # gpt-4, gpt-3.5-turbo, etc.